/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    input button,
    input button2,
    input button3,
    output reg high1,
    output reg high2,
    output reg high3,
    output reg low1,
    output reg low2,
    output reg low3
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_reset_cond2_out;
  reg [1-1:0] M_reset_cond2_in;
  reset_conditioner_1 reset_cond2 (
    .clk(clk),
    .in(M_reset_cond2_in),
    .out(M_reset_cond2_out)
  );
  wire [1-1:0] M_reset_cond3_out;
  reg [1-1:0] M_reset_cond3_in;
  reset_conditioner_1 reset_cond3 (
    .clk(clk),
    .in(M_reset_cond3_in),
    .out(M_reset_cond3_out)
  );
  wire [2-1:0] M_mymain_result;
  wire [1-1:0] M_mymain_high1;
  wire [1-1:0] M_mymain_high2;
  wire [1-1:0] M_mymain_high3;
  wire [1-1:0] M_mymain_low1;
  wire [1-1:0] M_mymain_low2;
  wire [1-1:0] M_mymain_low3;
  reg [1-1:0] M_mymain_left2;
  reg [1-1:0] M_mymain_center1;
  reg [1-1:0] M_mymain_right0;
  main_4 mymain (
    .clk(clk),
    .rst(rst),
    .left2(M_mymain_left2),
    .center1(M_mymain_center1),
    .right0(M_mymain_right0),
    .result(M_mymain_result),
    .high1(M_mymain_high1),
    .high2(M_mymain_high2),
    .high3(M_mymain_high3),
    .low1(M_mymain_low1),
    .low2(M_mymain_low2),
    .low3(M_mymain_low3)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    M_reset_cond2_in = ~rst_n;
    rst = M_reset_cond2_out;
    M_reset_cond3_in = ~rst_n;
    rst = M_reset_cond3_out;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    M_mymain_left2 = !button;
    M_mymain_center1 = !button2;
    M_mymain_right0 = !button3;
    high1 = M_mymain_high1;
    high2 = M_mymain_high2;
    high3 = M_mymain_high3;
    low1 = M_mymain_low1;
    low2 = M_mymain_low2;
    low3 = M_mymain_low3;
    led[0+1-:2] = M_mymain_result;
  end
endmodule
