/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_13 (
    input [7:0] a,
    input [7:0] b,
    input [5:0] alufn,
    output reg z,
    output reg v,
    output reg n,
    output reg [7:0] alu
  );
  
  
  
  reg [15:0] alu1;
  
  reg [0:0] n1;
  
  reg [0:0] v1;
  
  reg [0:0] z1;
  
  always @* begin
    n1 = 1'h0;
    v1 = 1'h0;
    z1 = 1'h0;
    
    case (alufn)
      6'h02: begin
        alu1 = a * b;
      end
      6'h00: begin
        alu1 = a + b;
        n1 = alu1[7+0-:1];
        if (alu1[0+7-:8] == 8'h00) begin
          z1 = 1'h1;
        end
        v1 = a[7+0-:1] & b[7+0-:1] & (~n1) | (~a[7+0-:1]) & (~b[7+0-:1]) & n1;
      end
      6'h01: begin
        alu1 = a - b;
        n1 = alu1[7+0-:1];
        if (alu1[0+7-:8] == 8'h00) begin
          z1 = 1'h1;
        end
        v1 = a[7+0-:1] & (~b[7+0-:1]) & (~n1) | (~a[7+0-:1]) & b[7+0-:1] & n1;
      end
      6'h20: begin
        alu1 = a << b[0+2-:3];
      end
      6'h21: begin
        alu1 = a >> b[0+2-:3];
      end
      6'h23: begin
        alu1 = $signed(a) >>> b[0+2-:3];
      end
      6'h18: begin
        alu1 = a & b;
      end
      6'h1e: begin
        alu1 = a | b;
      end
      6'h16: begin
        alu1 = a ^ b;
      end
      6'h1a: begin
        alu1 = a;
      end
      6'h35: begin
        if ($signed(a) < $signed(b)) begin
          alu1 = 8'h01;
        end else begin
          alu1 = 8'h00;
        end
      end
      6'h37: begin
        if ($signed(a) <= $signed(b)) begin
          alu1 = 8'h01;
        end else begin
          alu1 = 8'h00;
        end
      end
      6'h33: begin
        if ($signed(a) == $signed(b)) begin
          alu1 = 8'h01;
        end else begin
          alu1 = 8'h00;
        end
      end
    endcase
    v = v1;
    n = n1;
    z = z1;
    alu = alu1[0+7-:8];
  end
endmodule
