/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module propogate_9 (
    input clk,
    input rst,
    input [2:0] num,
    output reg [1:0] rowLit,
    output reg [2:0] numSeq,
    output reg row1,
    output reg row2,
    output reg row3,
    output reg gnd1,
    output reg gnd2,
    output reg gnd3,
    output reg propClk
  );
  
  
  
  wire [2-1:0] M_ctr_value;
  counter_17 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  wire [1-1:0] M_propClk1_value;
  counter_18 propClk1 (
    .clk(clk),
    .rst(rst),
    .value(M_propClk1_value)
  );
  
  always @* begin
    propClk = M_propClk1_value;
    row1 = 1'h0;
    row2 = 1'h0;
    row3 = 1'h0;
    gnd1 = ~num[0+0-:1];
    gnd2 = ~num[1+0-:1];
    gnd3 = ~num[2+0-:1];
    numSeq = num;
    rowLit = M_ctr_value;
    
    case (M_ctr_value)
      2'h0: begin
        row1 = 1'h1;
        row2 = 1'h0;
        row3 = 1'h0;
      end
      2'h1: begin
        row1 = 1'h0;
        row2 = 1'h1;
        row3 = 1'h0;
      end
      2'h2: begin
        row1 = 1'h0;
        row2 = 1'h0;
        row3 = 1'h1;
      end
      2'h3: begin
        row1 = 1'h0;
        row2 = 1'h0;
        row3 = 1'h0;
      end
    endcase
  end
endmodule
